# Generated by Django 4.0.4 on 2022-10-28 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alphabet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('katakana', models.JSONField(unique=True)),
                ('hiragana', models.JSONField(unique=True)),
                ('hangul', models.JSONField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='J6kSentences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('japaneseWord', models.TextField()),
                ('englishWord', models.TextField()),
                ('sentenceOne', models.JSONField()),
                ('englishSentenceOne', models.TextField()),
                ('sentenceTwo', models.JSONField()),
                ('englishSentenceTwo', models.TextField()),
                ('sentenceThree', models.JSONField()),
                ('englishSentenceThree', models.TextField()),
                ('sentenceNumber', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JSentences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessonSentence', models.JSONField()),
                ('sentenceNumber', models.IntegerField(unique=True)),
                ('englishSentence', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='KJESentences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('japaneseSentence', models.JSONField()),
                ('koreanSentence', models.JSONField()),
                ('englishSentence', models.TextField()),
                ('koreanWord', models.TextField()),
                ('japaneseWord', models.TextField()),
                ('englishWord', models.TextField()),
                ('sentenceNumber', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='KSentences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessonSentence', models.JSONField()),
                ('sentenceNumber', models.IntegerField(unique=True)),
                ('englishSentence', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='KSentenceSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentenceSplit', models.JSONField()),
                ('sentence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend_server.ksentences')),
            ],
        ),
        migrations.CreateModel(
            name='KJESentenceSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('japaneseSentence', models.JSONField()),
                ('koreanSentence', models.JSONField()),
                ('sentence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend_server.kjesentences')),
            ],
        ),
        migrations.CreateModel(
            name='JSentenceSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentenceSplit', models.JSONField()),
                ('sentence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend_server.jsentences')),
            ],
        ),
        migrations.CreateModel(
            name='J6kSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentenceOne_split', models.JSONField()),
                ('sentenceTwo_split', models.JSONField()),
                ('sentenceThree_split', models.JSONField()),
                ('sentence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend_server.j6ksentences')),
            ],
        ),
    ]
