import { DescriptionBox } from 'components/DescriptionBox'
import { Header } from 'components/Header'
import { Skewed } from 'components/Skewed'

import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Skewed />
      <Header title={'The Best way to learn'} />

      <DescriptionBox />
    </>
  )
}

export default Home
